@extends('layouts.master') @section('title', 'Privacy Policy') @section('imports')
<link rel="stylesheet" type="text/css" href="{{asset('css/referral.css')}}">
<script type="text/javascript" src="{{asset('js/referraltype.js')}}"></script>
@endsection @section('sidebar') @include('layouts.sidebar') @endsection @section('content')


<div class="content-section active" id="referral_types">

    <div class="row content-row-margin">
        <div class="col-xs-12 section-header">
            <span class=""><strong>OCUHUB PRIVACY POLICY</strong></span>
        </div>
        <p><strong>Last Updated: November 15, 2014</strong></p>
        <p>OcuHub LLC (“<strong>OcuHub</strong>,” “<strong>us</strong>” or “<strong>we</strong>”) values the privacy of our users, members, and others (collectively or individually “<strong>Users</strong>”) who visit and use the services available via OcuHub’s websites and associated services (collectively, the “<strong>Service</strong>”). This statement governs information you provide to us or that we learn from your use of the Service and tells you how we may collect, use, and in some instances share, this information.</p>
        <p><strong>The Information OcuHub Collects</strong></p>
        <p><strong>User Provided Information</strong>: You may provide to OcuHub what is generally called “personally identifiable” information when you register, such as your name and e-mail address. In addition, OcuHub may give you the option to provide us with certain demographic information about yourself and to upload photographs or other personally identifiable information.</p>
        <p><strong>“Cookies” Information</strong>: When you visit the Service, we may send one or more cookies – a small text file containing a string of alphanumeric characters – to your computer. OcuHub uses both session cookies and persistent cookies. A persistent cookie remains after you close your browser and may be used by your browser on subsequent visits to the Service. By using these cookies, we can “remember” what you have done on the Service before and personalize our site for you. These persistent types of cookies can be removed. Each web browser implements different functionality, so please refer to the manuals or technical support resources that are available in conjunction with your web browser to learn the correct way to modify your cookies set-up. If you are using the Service in a jurisdiction where your prior consent is required for us to deploy any particular cookies, you will be asked to accept such cookies before they are deployed. Please note that disabling cookies or declining to accept certain cookies will prevent you from accessing some of the functionality and site offerings available via the Service.</p>
        <p><strong>“Automatically Collected” Information</strong>: When you visit the Service or open one of our HTML emails, we may record certain information from your web browser by using different types of technology, including “clear gifs” or “web beacons.” This “automatically collected” information may include your Internet Protocol address (“<strong>IP Address</strong>”), web browser type, the web pages or sites that you visit just before or just after the Service, the pages you view on our site, and the dates and times that you visit.</p>
        <p><strong>Payment Information</strong>: If you purchase services directly from OcuHub, we may collect the billing and financial information necessary to process your charges, which may include your postal and e-mail addresses. OcuHub may also receive the billing and payment information that you provide when your purchase is processed by another party, such as PayPal.</p>
        <p><strong>Customer Support Correspondence</strong>: When you ask for assistance from our Customer Support team, we will collect and store the contact information you provide (generally your name and e-mail address), information about your activity on the Service, and your user ID number. We will also store the correspondence and any information contained within.</p>
        <p><strong>The Way OcuHub Uses Information</strong><em><br>
</em>OcuHub uses the information that we collect to provide to you all of the features and services foun on the Service. We may use your email address for marketing purposes, unless you have expressly notified us that you prefer for us not to use your email address for any specific marketing purposes (“opt-out”). While you may opt-out from such marketing use, you may not opt-out from our use of your email address for non-marketing or administrative purposes such as automatic notifications of recent account activity, or notifying you of major site updates.</p>
        <p>OcuHub may use all of the information that we collect from our Users to understand the usage trends and preferences, to improve the way the Service works and looks, to improve our marketing and promotional efforts, and to create new features and functionality.</p>
        <p>As part of this process, we may use Google Analytics to provide us with aggregated information about how Users interact with the Service, and may set cookies and/or use web beacons for this purpose. The information gathered by the Google Analytics software (including any personal information about you) will be sent to Google where it will be stored and used by Google in accordance with its own privacy policy rather than ours. Please review the Google Privacy Policy <a href="http://www.google.com/policies/privacy/">http://www.google.com/policies/privacy/</a> or contact Google for more information.</p>
        <p>OcuHub allows other users to view your name, other profile details and photographs should you provide this information and make it publicly viewable.</p>
        <p>OcuHub may use automatically collected information and cookies information to: (a) remember your information so that you will not have to re-enter it during your visit or the next time you visit the Service; (b) provide custom, personalized advertisements, content and information; (c) monitor the effectiveness of our marketing campaigns; and (d) monitor aggregate usage metrics such as total number of visitors and pages viewed.</p>
        <p>OcuHub will not use your email address or other personally identifiable information to send promotional or marketing messages except for those specific programs or features for which you will have the ability to opt-out.</p>
        <p><strong>When OcuHub Discloses Information<br>
</strong>OcuHub may disclose both personally identifiable and automatically collected information to affiliated companies or other businesses or persons to process such information on our behalf, to provide website maintenance and security, to offer certain features on the Service, to assist us in improving the way the Service works and looks, and to create new features. We require that these parties agree to process such information in compliance with our Privacy Policy, we use reasonable efforts to limit their use of such information, and we require these parties to use any other appropriate confidentiality and security measures.</p>
        <p>OcuHub may share automatically collected and other aggregated non-personally-identifiable information such as mobile device identifying information with interested third parties for their use and distribution for their business purposes, including without limitation for the purposes of assisting them in understanding the usage patterns for certain content, services, advertisements, and promotions.</p>
        <p>We may share personally identifiable information with other third-party organizations for their marketing or promotional use without your consent, except with respect to any specific program or feature for which you will have the ability to opt-out.</p>
        <p>We may disclose your personally identifiable information if we believe in good faith that such disclosure is necessary to (a) comply with laws or to respond to subpoenas, court orders, warrants or other legal demands or to establish or defend OcuHub from legal claims; or (b) to protect and defend our rights or property, you, or third parties from fraud, abuse or violations of the Terms of Service or illegal acts; or (c) to protect the safety or integrity of OcuHub, its users, the public or other parties as it is deemed appropriate, in our sole discretion. You hereby consent to our sharing your personally identifying information under the circumstances described herein.</p>
        <p>Except as otherwise noted in this Privacy Policy, OcuHub does not share personal information about Users with third parties unless doing so is appropriate to carry out a User’s request or it reasonably believes that doing so is legally required or is in OcuHub’ interest to protect its property or other legal rights or the rights or property of others.</p>
        <p><strong>User Profile and Password<br>
</strong>You have access to your personal information and you may update, correct, or delete your member information and email preferences at any time.</p>
        <p>To protect your privacy and security, we take reasonable steps to verify your identity before granting Users profile access. YOU ARE RESPONSIBLE FOR MAINTAINING THE SECRECY OF YOUR UNIQUE PASSWORD AND ACCOUNT INFORMATION AT ALL TIMES.</p>
        <p>PLEASE NOTE THAT WITH THE EXCEPTION OF CERTAIN CATEGORIES OF INFORMATION AS IDENTIFIED BY OCUHUB FROM TIME TO TIME, ALL INFORMATION THAT YOU POST FOR VIEWING ON THE SERVICE IS MADE PUBLICLY AVAILABLE TO ALL USERS OF THE SERVICE.</p>
        <p><strong>Children<br>
</strong>Consistent with the federal Children’s Online Privacy Protection Act of 1998 (COPPA), we do not intend to collect personally identifiable information from anyone under the age of thirteen (13). Any person who provides their personal information to OcuHub through the Service represents that they are 13 years of age or older.</p>
        <p><strong>Choice/Opt-Out<br>
</strong>Service provides you with the opportunity to affirmatively opt-out of receiving communications from us and our partners at the point where we request information about you. Service gives you the option to end our use of your information, and to cease receiving or otherwise having access to future communications or services.</p>
        <p><a href="mailto:OptOut@OcuHub.com">OptOut@OcuHub.com</a></p>
        <p><strong>Third Parties, Links to Other Sites<br>
</strong>OcuHub may allow other companies to display and transmit material via the Service and to users of the Service. This may include use of third-party functionality or features. It may also include third-party ad servers or ad networks to serve advertisements within the Service. Such third-party providers may use technology to send, directly to your browser, the advertisements, material and links that appear within the Service. They may automatically receive your IP Address when this happens. They may also use other technologies (such as cookies, JavaScript, or web beacons) to measure the effectiveness of their advertisements and to personalize their content.</p>
        <p>OcuHub may provide personally identifiable information to these third-party providers except as part of a specific program or feature for which you will have the ability to opt-in.</p>
        <p>Please note that if an advertiser asks OcuHub to show an advertisement to a certain audience or audience segment and you respond to that advertisement, the advertiser or ad-server may conclude that you fit the description of the audience they were trying to reach.</p>
        <p>You should consult the respective privacy policies of third-party providers for information regarding their use, collection and disclosure practices. OcuHub’ Privacy Policy does not apply to, and we cannot control the activities of, such third-party providers or their websites.</p>
        <p><strong>Our Commitment to Data Security<br>
</strong>No data transmissions over the Internet can be guaranteed to be 100% secure. Consequently, we cannot ensure or warrant the security of any information you transmit to us and you do so at your own risk. Once we receive your transmission, we make reasonable efforts to ensure security on our systems. We use secure server software (SSL) and firewalls to protect your information from unauthorized access, disclosure, alteration, or destruction. However, please note that this is not a guarantee that such information may not be illegally or improperly accessed, disclosed, altered, or destroyed by breach of such firewalls and secure server software.</p>
        <p>If OcuHub learns of a security systems breach, then we may attempt to notify you electronically so that you can take appropriate protective steps. By using the Service or providing personal information to us, you agree that we can communicate with you electronically regarding security, privacy, and administrative issues relating to your use of the Service. OcuHub may post a notice on the Service if a security breach occurs. If this happens, you will need a web browser enabling you to view the Service. OcuHub may also send an email to you at the email address you have provided to us in these circumstances. Depending on where you live, you may have a legal right to receive notice of a security breach in writing. To receive a free written notice of a security breach (or to withdraw your consent from receiving electronic notice) you should notify us via email at [support@OcuHub.com].</p>
        <p><strong>Special Note to International Users<br>
</strong>The Service is hosted in the United States and is only available to users who are residents of the United States. If you are a User accessing the Service outside of the United States, you will not be able to use the Service</p>
        <p><strong>In the Event of Merger or Sale<br>
</strong>If OcuHub should ever file for bankruptcy or have its assets sold to or merge with another entity, information OcuHub receives from you through the Service is an OcuHub asset and may be transferred to another party; however, in the event of such a transfer, we will require that the transferee agree to honor this Privacy Policy, as it applies to Users prior to the effective date of any such transfer, unless we are legally prohibited from doing so.</p>
        <p><strong>Changes and Updates to this Privacy Policy<br>
</strong>OcuHub reserves the right, at our discretion, to change, modify, add, or remove portions of this Privacy Policy at any time for any reason, and we may notify you of such changes through any of a variety of means, including a change to the “Last Updated” date set forth above and other reasonable means to be determined at our discretion. All changes shall be effective immediately. In the event of a material change that may directly affect your account, we will notify you via the most recent e-mail address that you have provided to us in conjunction with your account. Please check this Privacy Policy periodically for changes. Your continued use of the Service after the posting of changes constitutes your binding acceptance of such changes.</p>
        <p><strong>Contacting OcuHub<br>
</strong>If you have any questions, comments, or concerns about this Privacy Policy, please email us at <a href="mailto:support@OcuHub.com">support@OcuHub.com</a> or write to us at:</p>
        <p>Postal Mail Address: OcuHub LLC, 4885 Olde Towne Parkway, Suite 200, Marietta, GA 30068.</p>
    </div>

</div>

@endsection
