@extends('layouts.master') @section('title', 'Terms of use') @section('imports')
<link rel="stylesheet" type="text/css" href="{{asset('css/referral.css')}}">
<script type="text/javascript" src="{{asset('js/referraltype.js')}}"></script>
@endsection @section('sidebar') @include('layouts.sidebar') @endsection @section('content')


<div class="content-section active" id="referral_types">

    <div class="row content-row-margin">
        <div class="col-xs-12 section-header">
            <strong><span class="">OCUHUB TERMS OF USE</span></strong>
        </div>
        <div id="mk-text-block-511" style=" margin-bottom:0px;text-align: left;" class="mk-text-block  ">
<!--
            <h3><strong>OCUHUB TERMS OF USE<br>
</strong></h3>
-->
            <p><strong>Last Updated: November&nbsp;15, 2014</strong></p>
            <p>The following Terms of Use apply to all users of services available via online websites and services (collectively, the “Service”), as provided to you by OcuHub LLC, a Delaware limited liability company (“OcuHub”). The following Terms of Use for the Service is a legal contract between you, an individual user or a single entity (collectively or individually “Users”), and OcuHub regarding your use of the Service. Together, Users and OcuHub are each referred to herein individually as a “Party” or collectively as the “Parties”. When using the Service, you may be subject to any additional posted guidelines or rules applicable to specific services and features which may be posted from time to time (the “Guidelines”), as well as any separate agreements between you and OcuHub governing your use of the Service. All such agreements and Guidelines are hereby incorporated by reference into these Terms of Use.</p>
            <p>BEFORE USING THE SERVICE, PLEASE READ THE FOLLOWING TERMS OF USE CAREFULLY. BY REGISTERING FOR AND/OR ACCESSING, BROWSING, OR USING THE SERVICE, YOU ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE BOUND BY THE FOLLOWING TERMS (COLLECTIVELY, THE “TERMS OF USE” OR “TERMS”).</p>
            <p>1.&nbsp;<strong>Eligibility.</strong>&nbsp;In order to use the Service, you must either be the age of majority in your jurisdiction, an emancipated minor, or possess legal parental or guardian consent, and fully able and competent to enter into the terms, conditions, obligations, affirmations, representations and warranties set forth in these Terms and to abide by and comply with these Terms. You represent that you meet the eligibility requirements in this Section. In any case, you affirm that you are over the age of 13, as the Service is not intended for children under 13. If you are between the ages of 13 and 17, you represent that your legal guardian has reviewed and agreed to these Terms. The Service is only available to residents of the United States.</p>
            <p>2.&nbsp;<strong>Privacy Notice.</strong>&nbsp;Your privacy is important to OcuHub. OcuHub’s Privacy Policy <a href="http://www.ocuhub.com/privacypolicy">www.OcuHub.com/privacypolicy</a> is hereby incorporated into these Terms by reference. Please read this policy carefully for information relating to OcuHub’s collection, use, and disclosure of your personal information.</p>
            <p>3.&nbsp;<strong>Modification of the Terms.</strong>&nbsp;OcuHub reserves the right, at our discretion, to change, modify, add, or remove portions of these Terms at any time for any reason, and we may notify you of such changes through any of a variety of means, including a change to the “Last Updated” date set forth above and other reasonable means to be determined at our discretion. All changes shall be effective immediately. In the event of a material change that may directly affect your account, we may notify you via the most recent e-mail address that you have provided to us in conjunction with your account. Please check these Terms periodically for changes. Your continued use of the Service after the posting of changes constitutes your binding acceptance of such changes.</p>
            <p>4.&nbsp;<strong>Service Access and Use.</strong>&nbsp;OcuHub grants you permission to use the Service as set forth in these Terms, provided that and for so long as (i) you use the Service solely for your personal or business use; (ii) except as expressly permitted in these Terms, you do not download, reproduce, redistribute, retransmit, publish, resell, distribute, publicly display or otherwise exploit any portion of the Service in any medium without OcuHub’s prior written authorization; (iii) you do not alter or modify any part of the Service other than as may be reasonably necessary to use the Service for its intended purposes; (iv) you do not engage in any of the prohibited uses described below; and (v) you otherwise fully comply with these Terms. The Service is controlled and offered by OcuHub from its facilities in the United States and is not available to users outside the United States.</p>
            <p>5.&nbsp;<strong>Ownership; Proprietary Rights.</strong>&nbsp;The Service including without limitation any methods of operation, moral rights, documentation, software, content, visual interfaces, interactive features, information, graphics, design, compilation, computer code, products, services, and all other elements of the Service that are provided by OcuHub (“OcuHub Materials”) are owned and/or licensed by OcuHub. OcuHub Materials do not include Contributed Content (as defined below). Except as expressly authorized by OcuHub, you agree not to sell, license, distribute, copy, modify, publicly perform or display, transmit, publish, edit, adapt, create derivative works from, or otherwise make unauthorized use of the Service or the OcuHub Materials. OcuHub reserves all rights not expressly granted in these Terms. You shall not acquire any right, title, or interest to the OcuHub Materials, except for the limited rights set forth in these Terms.</p>
            <p>6.&nbsp;<strong>User Content.<br>
</strong>(a) General. The Service may now or in the future permit you and other Users to create, post, transmit or link media, text, audio and video recordings, photos, graphics, commentary or other information or content (“User Content”), and to host and/or share such User Content. User Content is not controlled by OcuHub. OcuHub makes no representations that your User Content will remain available via the Service in any way and may remove your User Content in its sole discretion. YOU UNDERSTAND THAT ANY USER CONTENT THAT YOU POST FOR VIEWING ON THE SERVICE IS MADE PUBLICLY AVAILABLE TO USERS OF THE SERVICE, AND OCUHUB DOES NOT GUARANTEE ANY CONFIDENTIALITY WITH RESPECT TO ANY SUCH USER CONTENT. NOR DOES OCUHUB GUARANTEE THAT YOUR INTELLECTUAL OR PROPRIETARY RIGHTS IN SUCH USER CONTENT WILL NOT BE INFRINGED OR MISAPPROPRIATED.</p>
            <p>(b) Grant of Rights. By submitting User Content to OcuHub, you hereby grant OcuHub and its affiliates a worldwide, non-exclusive, fully paid-up, royalty-free, transferable license, with the right to grant and authorize sublicenses, to use, reproduce, distribute, modify, adapt, translate, prepare derivative works of, display, perform, and otherwise exploit your User Content in connection with the Service and OcuHub’s (and its successor’s, transferees’, sublicensees’ and their respective affiliates’) (collectively the “OcuHub Parties”) business. You grant the OcuHub Parties the right to use the name that you submit or display in connection with such User Content if they choose. You also agree to irrevocably waive (and cause to be waived) any claims and assertions of moral rights or attribution with respect to your User Content. You also hereby grant to each user of the Service a non-exclusive license to access your User Content through the Service, and to use, reproduce, distribute, modify, adapt, translate, prepare derivative works of, display, and perform such User Content as permitted by the functionality of the Service and these Terms<strong>. The above licenses granted by you in User Content you submit to the Service shall be perpetual and irrevocable</strong>.</p>
            <p>(c) Your Representations and Warranties Regarding User Content. You shall be solely responsible for your own User Content and the consequences of posting such Content. In connection with User Content, you affirm, represent, and/or warrant that: (i) you own, or have the necessary licenses, rights, consents, and permissions to use and authorize the OcuHub Parties to use, all patent, trademark, copyright, or other proprietary rights in and to any and all User Content to enable inclusion and use of User Content in the manner contemplated by the OcuHub Parties and these Terms, and to grant the rights and license set forth in this Section, and (ii) your User Content, the OcuHub Parties’ use of such User Content pursuant to these Terms, and the OcuHub Parties’ exercise of the license rights set forth in this Section, do not and will not: (A) infringe, violate, or misappropriate any third-party right, including any copyright, trademark, patent, trade secret, moral right, privacy right, right of publicity, or any other intellectual property or proprietary right; (B) slander, defame, libel, or invade the right of privacy, publicity or other property rights of any other person; or (C) violate any applicable law or regulation.</p>
            <p>(d) Prohibited Uses of User Content. Except as otherwise permitted by these Terms, in connection with your User Content, you further agree that you will not publish, post, submit, transmit through or otherwise make available to the Service : (i) any falsehoods or misrepresentations that could damage OcuHub or any third party; (iii) any material which is unlawful, defamatory, libelous, slanderous, pornographic, obscene, abusive, profane, vulgar, sexually explicit, threatening, harassing, harmful, hateful, racially or ethnically offensive or otherwise objectionable, or which encourages conduct that would be considered a criminal offense, give rise to civil liability, violate any law or any right of privacy or publicity, or is otherwise inappropriate; (iv) advertisements or solicitations of business, products, or services; or (v) any material that would be harmful to minors in any manner.</p>
            <p>(e) No Responsibility for User Content. With the exception of the limited license granted above, we do not obtain or control any rights in, and do not exert editorial control over, User Content. Nothing herein obligates us to verify, and we have not necessarily verified, the representations and warranties made by Users with respect to such User Content.</p>
            <p>7.&nbsp;<strong>Contributed Content Disclaimer</strong>. You understand that when using the Service you will be exposed to material not originating from OcuHub, including User Content, advertising and other third-party content (together, the “Contributed Content”) from a variety of sources, and that you may be exposed to Contributed Content that is inaccurate, offensive, indecent, or otherwise objectionable. OcuHub does not endorse any Contributed Content or any opinion, recommendation, or advice expressed therein. Under no circumstances will OcuHub be liable in any way for or in connection with the Contributed Content, including, but not limited to, for any inaccuracies, errors or omissions in any Contributed Content, any intellectual property infringement with regard to any Contributed Content, or for any loss or damage of any kind incurred as a result of the use of any non-OcuHub Content posted, emailed or otherwise displayed or transmitted through the Service.</p>
            <p>8.&nbsp;<strong>Non-Monitoring of Users and Contributed Content.</strong>&nbsp;You understand that you, and not OcuHub, are entirely responsible for all User Content that you upload, post, e-mail, transmit or otherwise make available through the Service. OcuHub does not control Contributed Content and does not have any obligation to monitor such Contributed Content for any purpose. If at any time OcuHub chooses, in its sole discretion, to monitor the Contributed Content, OcuHub nonetheless assumes no responsibility for the Contributed Content, no obligation to modify or remove any inappropriate Contributed Content, and no responsibility for the conduct of the User or other person or entity submitting any such Contributed Content. You agree that you must evaluate, and bear all risks associated with the use of any User Content or other Contributed Content, including any reliance on the accuracy, completeness, usefulness, or legality of such User Content or other Contributed Content.</p>
            <p>9.&nbsp;<strong>Removal of Contributed Content.</strong>&nbsp;OcuHub and its designees shall have the right (but not the obligation) in their sole discretion to refuse to post or remove any Contributed Content that is available on the Service in whole or in part at any time for any reason or no reason, with or without notice and with no liability of any kind.</p>
            <p>10.&nbsp;<strong>Prohibited Uses of the Service.<br>
</strong>(a) As a condition of your use of the Service, you hereby represent and warrant that you will not use the Service for any purpose that is unlawful or prohibited (including, without limitation, the prohibitions in this Section) by these Terms.</p>
            <p>(b) Any use by you of any of the OcuHub Materials and Service other than (1) as an authorized business account holder subject to a separate agreement with OcuHub or (2) for your personal non-commercial use is strictly prohibited, including but not limited to communicating or facilitating any commercial advertisement or solicitation. You agree not to reproduce, duplicate, copy, sell, trade, resell, distribute, or exploit any portion of the Service, use of the Service, access to the Service, or Contributed Content obtained through the Service, for any purpose other than for your personal or authorized business use.</p>
            <p>(c) You agree not to use the Service if you do not meet the eligibility requirements described in Section 1 above.</p>
            <p>(d) You agree not to defame, harass, abuse, threaten, stalk or defraud Users of the Service, or collect, or attempt to collect, personal information about Users or third parties without their consent.</p>
            <p>(e) You agree not to intentionally interfere with or damage, impair or disable the operation of the Service or any User’s enjoyment of it by any means, including but not limited to uploading or otherwise disseminating viruses, worms, spyware, adware, or other malicious code, or placing a disproportionate load on the Service with the intended result of denying service to other Users.</p>
            <p>(f) You agree not to remove, circumvent, disable, damage or otherwise interfere with any security- related features of the Service, features that prevent or restrict the use or copying of any part of the Service, or features that enforce limitations on the use of the Service.</p>
            <p>(g) You agree not to attempt to gain unauthorized access to the Service or any part of it, other accounts, computer systems or networks connected to the Service or any part of it, through hacking, password mining or any other means or interfere or attempt to interfere with the proper working of the Service or any activities conducted through the Service.</p>
            <p>(h) You agree not to obtain or attempt to obtain any materials or information through any means not intentionally made available through the Service. You agree neither to modify the Service in any manner or form (other than contributing User Content as enabled by the Service’s functionality and in accordance with these Terms), nor to use modified versions of the Service, including (without limitation) for the purpose of obtaining unauthorized access to the Service.</p>
            <p>(i) You agree that you will not use any robot, spider, scraper, or other automated means to access the Service for any purpose without our express written permission or bypass our robot exclusion headers or other measures we may use to prevent or restrict access to the Service.</p>
            <p>(j) You agree not to utilize framing techniques to enclose any trademark, logo, or other OcuHub Materials without our express written consent. You agree not to use any meta tags or any other “hidden text” utilizing OcuHub’s name or trademarks without OcuHub’s express written consent.</p>
            <p>(k) You agree not to use any OcuHub logos, graphics, or trademarks as part of any link without our express written consent.</p>
            <p>(l) You agree not to make unsolicited offers, advertisements, proposals, or send junk mail or spam to other users of the Service. This includes, but is not limited to, unsolicited advertising, promotional materials or other solicitation material, bulk mailing of commercial advertising, chain mail, informational announcements, charity requests, and petitions for signatures, regardless whether by digital, postal, telephonic or other means.</p>
            <p>(m) You agree not to reverse engineer, decompile, disassemble or otherwise attempt to discover the source code of the Service or any part thereof, except and only to the extent that such activity is expressly permitted by applicable law notwithstanding this limitation.</p>
            <p>(n) You agree not to modify, adapt, translate, or create derivative works based upon the Service or any part thereof, except and only to the extent that such activity is expressly permitted by applicable law notwithstanding this limitation.</p>
            <p>(o) You agree not to impersonate another person or entity, or falsely state or otherwise misrepresent your affiliation with a person or entity.</p>
            <p>(p) You agree to monitor your user account to restrict use by minors, and you will deny access to children under the age of 13. You accept full responsibility for any unauthorized use of the Service by minors in connection with your user account.</p>
            <p>(q) You agree not to have more than one user account at any given time, and shall not create an user account using a false identity or information, or on behalf of someone other than yourself.</p>
            <p>(r) You agree not to have a user account or use the Service if you have previously been removed by OcuHub or previously been banned from using the Service.</p>
            <p>(s) You agree not to use the Service if you are located outside of the United States.</p>
            <p>(t) You agree not to transmit unauthorized communications through the Service, including junk mail, chain letters, spam and any materials that promote malware, spyware and downloadable items.</p>
            <p>(u) You agree not to solicit or attempt to solicit personal information from other users of the Service.</p>
            <p>(v) You agree not to collect, harvest or post anyone’s private information, including personally identifiable information (whether in text, image or video form), identification documents, or financial information through the Service.</p>
            <p>(w) You agree not to upload or transmit or attempt to upload or transmit, without OcuHub’s express permission, any material that acts as a passive or active information collection or transmission mechanism, including, without limitation, clear graphics interchange formats (“gifs”), 1×1 pixels, web bugs, cookies or other similar devices (sometimes referred to as “spyware,” “passive collection mechanisms” or “pcms”).</p>
            <p>(x) You agree not to engage in any act that OcuHub deems to be in conflict with the spirit or intent of the Service, including but not limited to circumventing or manipulating these Terms, our Service rules, Service mechanics or policies.</p>
            <p>(y) You agree not to make improper use of OcuHub’s support services, including by submitting false abuse reports or using profane and abusive language in your communications with our support personnel.</p>
            <p>(z) You agree not to use cheats, exploits, automation software, bots, hacks, mods or any unauthorized third party software designed to modify or interfere with the Service.</p>
            <p>11.&nbsp;<strong>Account Information.</strong>&nbsp; In order to access some features of the Service, you will have to create an account. You acknowledge, consent, and agree that OcuHub may access, preserve and disclose your account information and User Content if required to do so by law or in a good faith belief that such access, preservation or disclosure is reasonably necessary to (i) comply with legal process; (ii) enforce the Terms; (c) respond to any claim that User Content violates the rights of third parties; (iii) provide certain customized features of the Service to you, if any; (iv) respond if you contact OcuHub for any reason; or (v) protect the rights, property, or personal safety of OcuHub, its other Users, and the public.</p>
            <p>12.&nbsp;<strong>Password.</strong>&nbsp;If you register you will be asked to provide a password. As you will be responsible for all activities that occur under your password, you should keep your password confidential. You are solely responsible for maintaining the confidentiality of your account and password and for restricting access to your computer and mobile devices, and you agree to accept responsibility for all activities that occur under your account or password. If you have reason to believe that your account is no longer secure (for example, in the event of a loss, theft, or unauthorized disclosure or use of your account ID or password), you shall immediately notify OcuHub. YOU ARE SOLELY LIABLE FOR LOSSES INCURRED BY YOU, OCUHUB OR OTHERS DUE TO ANY UNAUTHORIZED USE OF YOUR ACCOUNT.</p>
            <p>13.&nbsp;<strong>Dealings with Third Parties and other Users.</strong>&nbsp;Your correspondence or business dealings with, or participation in promotions of, third parties such as advertisers and vendors, and other Users, found on or through the Service are solely between you and such third parties or Users. OcuHub reserves the right, but has no obligation, to become involved in any way with any disputes you may have with such parties. YOU AGREE THAT OCUHUB WILL NOT BE RESPONSIBLE OR LIABLE FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS THE RESULT OF ANY SUCH DEALINGS OR AS THE RESULT OF THE PRESENCE OF SUCH THIRD PARTIES OR USERS ON THE SERVICE.</p>
            <p>14.&nbsp;<strong>Links and Third Party Websites.</strong>&nbsp;OcuHub, Users and other third parties may provide links on the Service to other sites, including the content therein (“Reference Sites”). OcuHub has no control over such Reference Sites or their content, and therefore makes no claim or representation regarding, and expressly disclaims responsibility for, the accuracy, quality, legality, nature, availability, or reliability of Reference Sites or other content linked to by the Service. OcuHub provides links to you only as a convenience, and the inclusion of any link on the Service does not imply our affiliation, endorsement, or adoption of the linked Reference Site or other content or any information therein. ACCESS AND USE OF REFERENCE SITES, INCLUDING THE INFORMATION, CONTENT, MATERIAL, PRODUCTS, AND SERVICES ON REFERENCE SITES OR AVAILABLE THROUGH REFERENCE SITES, IS SOLELY AT YOUR OWN RISK. Our terms and policies do not govern your use of any site other than the Service. You should review applicable terms and policies, including the privacy and data gathering practices, of any Reference Sites.</p>
            <p>15.&nbsp;<strong>Service Availability.</strong>&nbsp;OcuHub may make changes to or discontinue any of the media, features, products, or services available within the Service at any time, and without notice. The media, features, products, or services on the Service may be out of date, and OcuHub makes no commitment to update these materials on the Service.</p>
            <p>16.&nbsp;<strong>Feedback.</strong>&nbsp;You agree that any feedback, analysis, suggestions and comments to OcuHub provided by you (collectively, “Feedback”) will become the property of OcuHub. IN CONSIDERATION OF OCUHUB PROVIDING ACCESS TO THE SERVICE FREE OF CHARGE OR, IN THE CASE OF FEEDBACK PROVIDED USING FEATURES OF THE SERVICE FOR WHICH YOU MUST PAY A FEE, THEN AS FURTHER CONSIDERATION FOR YOUR ACCESS TO SUCH FEATURES, USER HEREBY ASSIGNS TO OCUHUB ALL RIGHT, TITLE AND INTEREST, INCLUDING ALL INTELLECTUAL PROPERTY RIGHTS, IN AND TO THE FEEDBACK. WITHOUT LIMITING THE GENERALITY OF THE FOREGOING, USER AGREES THAT OCUHUB SHALL HAVE THE PERPETUAL, IRREVOCABLE AND WORLDWIDE RIGHT TO USE, COPY, DISPLAY, PERFORM, TRANSLATE, MODIFY, LICENSE, SUBLICENSE AND OTHERWISE EXPLOIT ALL OR PART OF THE FEEDBACK OR ANY DERIVATIVE THEREOF IN ANY EMBODIMENT, MANNER OR MEDIA NOW KNOWN OR HEREAFTER DEVISED WITHOUT ANY REMUNERATION, COMPENSATION OR CREDIT TO USER. User represents and warrants that User has the right to make the foregoing assignment and to grant to OcuHub the rights granted under this Section 16 and that any Feedback which is provided by User to OcuHub does not infringe any third-party intellectual property rights. Notwithstanding the foregoing assignment, OcuHub grants to you a non-exclusive, non-transferable, non-sublicensable, world-wide, perpetual and irrevocable license to use the Feedback for your own personal, non-commercial purposes that do not compete, directly or indirectly, with our use of such Feedback.</p>
            <p>17.&nbsp;<strong>User Disagreements.</strong>&nbsp;You are solely responsible for your involvement with other Users of the Service. OcuHub reserves the right, but has no obligation, to monitor disagreements between you and other Users. OCUHUB DISCLAIMS ALL LIABILITY RELATED TO ANY USER DISAGREEMENT.</p>
            <p>18.&nbsp;<strong>Terms of Use Violations; Termination.</strong> You agree that OcuHub, in its sole discretion, may terminate any account (or any part thereof) you may have through the Service or your use of the Service, and remove and discard all or any part of your account or any User Content. You agree that your access to the Service or any account you may have or portion thereof may be terminated without prior notice, and you agree that OcuHub shall not be liable to you or any third-party for any such termination. These remedies are in addition to any other remedies OcuHub may have at law or in equity.</p>
            <p>19.&nbsp;<strong>INDEMNIFICATION; HOLD HARMLESS.</strong>&nbsp;YOU AGREE TO INDEMNIFY AND HOLD HARMLESS OCUHUB, AND ITS PARENT, SUBSIDIARIES, AFFILIATES OR ANY RELATED COMPANIES (INCLUDING THOSE WHICH SHARE SUBSTANTIALLY COMMON OWNERSHIP), AND THE OFFICERS, DIRECTORS, EMPLOYEES, AGENTS AND REPRESENTATIVES OF ANY OF THEM FROM ANY AND ALL CLAIMS, LOSSES, OBLIGATIONS, DAMAGES, LIABILITIES, COSTS, DEBT, AND EXPENSES (INCLUDING ATTORNEY’S FEES) ARISING OUT OF (I) YOUR USE OR MISUSE OF THE SERVICE; (II) YOUR USER CONTENT, INCLUDING OCUHUB’S USE, DISPLAY OR OTHER EXERCISE OF ITS LICENSE RIGHTS GRANTED HEREIN WITH RESPECT TO YOUR USER CONTENT; (III) YOUR VIOLATION OF THESE TERMS; (IV) YOUR VIOLATION OF THE RIGHTS OF ANY OTHER PERSON OR ENTITY, INCLUDING CLAIMS THAT ANY USER CONTENT INFRINGES OR VIOLATES ANY THIRD PARTY INTELLECTUAL PROPERTY RIGHTS; (V) YOUR BREACH OF THE FOREGOING REPRESENTATIONS, WARRANTIES, AND COVENANTS; AND (VI) ANY UNAUTHORIZED USE OF YOUR ACCOUNT NOT CAUSED BY OCUHUB. OCUHUB RESERVES THE RIGHT, AT YOUR EXPENSE, TO ASSUME THE EXCLUSIVE DEFENSE AND CONTROL OF ANY MATTER FOR WHICH YOU ARE REQUIRED TO INDEMNIFY US AND YOU AGREE TO COOPERATE WITH OUR DEFENSE OF THESE CLAIMS. YOU AGREE NOT TO SETTLE ANY MATTER GIVING RISE TO YOUR INDEMNIFICATION OBLIGATIONS WITHOUT THE PRIOR WRITTEN CONSENT OF OCUHUB. OCUHUB WILL USE REASONABLE EFFORTS TO NOTIFY YOU OF ANY SUCH CLAIM, ACTION, OR PROCEEDING UPON BECOMING AWARE OF IT.</p>
            <p>20.<strong>&nbsp;DISCLAIMERS; NO WARRANTIES.</strong>
                <br> (a) ACKNOWLEDGMENT. YOU EXPRESSLY ACKNOWLEDGE THAT AS USED IN THIS SECTION 20, AND SECTIONS 21 AND 22 BELOW, THE TERM OCUHUB INCLUDES OCUHUB’S PARENT, SUBSIDIARY, AFFILIATED AND OTHER RELATED COMPANIES (INCLUDING THOSE WHICH SHARE SUBSTANTIALLY COMMON OWNERSHIP) AND EACH OF THEIR OFFICERS, DIRECTORS, EMPLOYEES, SHAREHOLDERS, MEMBERS, AGENTS AND SUBCONTRACTORS.</p>
            <p>(b) NO WARRANTIES. TO THE FULLEST EXTENT PERMISSIBLE PURSUANT TO APPLICABLE LAW, OCUHUB DISCLAIMS ALL WARRANTIES, STATUTORY, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT OF PROPRIETARY RIGHTS. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM OCUHUB OR THROUGH THE SERVICE, WILL CREATE ANY WARRANTY NOT EXPRESSLY STATED HEREIN.</p>
            <p>(c) “AS IS” AND “AS AVAILABLE” AND “WITH ALL FAULTS.” YOU EXPRESSLY AGREE THAT THE USE OF THE SERVICE IS AT YOUR SOLE RISK. THE SERVICE, USER CONTENT, CONTRIBUTED CONTENT, AND ANY OTHER THIRD-PARTY MEDIA, CONTENT, SOFTWARE, GOODS, SERVICES OR APPLICATIONS MADE AVAILABLE IN CONJUNCTION WITH OR THROUGH THE SERVICE ARE PROVIDED ON AN “AS IS” AND “AS AVAILABLE”, “WITH ALL FAULTS” BASIS AND WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED. WITHOUT LIMITING THE GENERALITY OF THE FOREGOING IN ANY WAY, YOU EXPRESSLY AGREE THAT THE SERVICE DOES NOT CONSTITUTE OR OFFER MEDICAL ADVICE OR SERVICES, AND THAT OCUHUB IS NOT A MEDICAL PRACTITIONER OR HEALTHCARE PROVIDER OF ANY KIND. OCUHUB DISCLAIMS ALL LIABILITY RELATED TO MEDICAL INFORMATION MADE AVAILABLE VIA THE SERVICE OR OBTAINED THEREFROM.</p>
            <p>(d) SERVICE OPERATION AND CONTRIBUTED CONTENT. OCUHUB DOES NOT WARRANT THAT THE OCUHUB MATERIALS, USER CONTENT, CONTRIBUTED CONTENT, SERVICE, OR ANY OTHER INFORMATION OFFERED ON OR THROUGH THE SERVICE OR ANY REFERENCE SITES WILL BE UNINTERRUPTED, OR FREE OF ERRORS, VIRUSES, OR OTHER HARMFUL COMPONENTS AND DOES NOT WARRANT THAT ANY OF THE FOREGOING WILL BE CORRECTED.</p>
            <p>(e) ACCURACY. OCUHUB DOES NOT WARRANT OR MAKE ANY REPRESENTATIONS REGARDING THE USE OR THE RESULTS OF THE USE OF THE SERVICE OR ANY REFERENCE SITES IN TERMS OF CORRECTNESS, ACCURACY, RELIABILITY, OR OTHERWISE.</p>
            <p>(f) HARM TO YOUR COMPUTER OR MOBILE DEVICE. YOU UNDERSTAND AND AGREE THAT YOUR USING, ACCESSING, DOWNLOADING, OR OTHERWISE OBTAINING INFORMATION, MATERIALS, OR DATA THROUGH THE SERVICE OR ANY REFERENCE SITES IS AT YOUR OWN DISCRETION AND RISK AND THAT YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR PROPERTY (INCLUDING YOUR COMPUTER SYSTEM OR MOBILE DEVICE) OR LOSS OF DATA THAT RESULTS FROM THE USE OR DOWNLOAD OF, OR OTHER ACCESS TO SUCH MATERIAL OR DATA.</p>
            <p>21.&nbsp;<strong>LIMITATION OF LIABILITY AND DAMAGES.</strong>
                <br> (a) LIMITATION OF LIABILITY. UNDER NO CIRCUMSTANCES, AND UNDER NO LEGAL THEORY, INCLUDING, BUT NOT LIMITED TO, NEGLIGENCE, SHALL OCUHUB OR ITS THIRD PARTY PARTNERS, LICENSORS OR SUPPLIERS, BE LIABLE FOR ANY SPECIAL, INDIRECT, INCIDENTAL, CONSEQUENTIAL, OR EXEMPLARY DAMAGES (INCLUDING, WITHOUT LIMITATION, LOSS OF PROFITS, DATA OR USE OR COST OF COVER) ARISING OUT OF OR RELATING TO THESE TERMS OR THAT RESULT FROM YOUR USE OF, OR THE INABILITY TO USE, THE OCUHUB MATERIALS AND USER CONTENT ON THE SERVICE OR ANY REFERENCE SITES, THE SERVICE ITSELF, OR ANY OTHER INTERACTIONS WITH OCUHUB, EVEN IF OCUHUB HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>
            <p>(b) LIMITATION OF DAMAGES. IN NO EVENT SHALL OCUHUB OR ITS THIRD PARTY PARTNERS, LICENSORS OR SUPPLIERS’ TOTAL LIABILITY TO YOU FOR ALL DAMAGES, LOSSES, AND CAUSES OF ACTION ARISING OUT OF OR RELATING TO THESE TERMS OR YOUR USE OF THE SERVICE (WHETHER IN CONTRACT, TORT (INCLUDING NEGLIGENCE), WARRANTY, OR OTHERWISE) EXCEED THE GREATER OF ONE HUNDRED DOLLARS (USD $100) OR ONE-HALF OF THE ANNUAL FEES PAID BY YOU (IF APPLICABLE) IN THE TWELVE (12) MONTHS IMMEDIATELY PRECEDING THE DATE THAT SUCH CLAIM AROSE.</p>
            <p>(c) THIRD PARTY PRODUCTS AND SERVICES. SOME USERS MAY USE THE SERVICE TO MARKET PRODUCTS AND/OR SERVICES. THE ABOVE LIMITATIONS SHALL ALSO APPLY WITH RESPECT TO DAMAGES INCURRED BY REASON OF ANY SUCH PRODUCTS OR SERVICES MARKETED, SOLD OR PROVIDED BY USERS, OR OTHERWISE BY THIRD PARTIES OTHER THAN OCUHUB AND RECEIVED BY YOU THROUGH OR ADVERTISED ON THE SERVICE OR THIRD PARTY SITES, INCLUDING WITHOUT LIMITATION ANY REFERENCE SITES.</p>
            <p>22.&nbsp;<strong>LIMITATIONS BY APPLICABLE LAW; BASIS OF THE BARGAIN.</strong></p>
            <p>(a) LIMITATIONS BY APPLICABLE LAW. CERTAIN JURISDICTIONS DO NOT ALLOW LIMITATIONS ON IMPLIED WARRANTIES OR THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES. IF YOU RESIDE IN SUCH A JURISDICTION, SOME OR ALL OF THE ABOVE DISCLAIMERS, EXCLUSIONS, OR LIMITATIONS MAY NOT APPLY TO YOU, AND YOU MAY HAVE ADDITIONAL RIGHTS. THE LIMITATIONS OR EXCLUSIONS OF WARRANTIES, REMEDIES, OR LIABILITY CONTAINED IN THESE TERMS APPLY TO YOU TO THE FULLEST EXTENT SUCH LIMITATIONS OR EXCLUSIONS ARE PERMITTED UNDER THE LAWS OF THE JURISDICTION IN WHICH YOU ARE LOCATED.</p>
            <p>(b) BASIS OF THE BARGAIN. YOU ACKNOWLEDGE AND AGREE THAT OCUHUB HAS OFFERED ITS PRODUCTS AND SERVICES AND ENTERED INTO THESE TERMS IN RELIANCE UPON THE WARRANTY DISCLAIMERS AND THE LIMITATIONS OF LIABILITY SET FORTH HEREIN, THAT THE WARRANTY DISCLAIMERS AND THE LIMITATIONS OF LIABILITY SET FORTH HEREIN REFLECT A REASONABLE AND FAIR ALLOCATION OF RISK BETWEEN YOU AND OCUHUB, AND THAT THE WARRANTY DISCLAIMERS AND THE LIMITATIONS OF LIABILITY SET FORTH HEREIN FORM AN ESSENTIAL BASIS OF THE BARGAIN BETWEEN YOU AND OCUHUB. YOU ACKNOWLEDGE AND AGREE THAT OCUHUB WOULD NOT BE ABLE TO PROVIDE THE SERVICE TO YOU ON AN ECONOMICALLY REASONABLE BASIS WITHOUT THESE LIMITATIONS.</p>
            <p>23.&nbsp;<strong>Digital Millennium Copyright Act Compliance.<br>
</strong>(a) Infringement Claims. If you are a copyright owner or an agent thereof, and believe that any User Content or other Contributed Content infringes upon your copyrights, you may submit a notification pursuant to the Digital Millennium Copyright Act (“DMCA”) by providing our Copyright Agent with the following information in writing (see 17 U.S.C 512(c)(3) for further detail).</p>
            <p>(i) A physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed;</p>
            <p>(ii) Identification of the copyrighted work claimed to have been infringed, or, if multiple copyrighted works are covered by a single notification, a representative listing of such works or a link or URL to all such works;</p>
            <p>(iii) Identification of the material that is claimed to be infringing or to be the subject of infringing activity on the Service and that is to be removed or access to which is to be disabled, including the link or URL for all such material on the Service;</p>
            <p>(iv) Information reasonably sufficient to permit OcuHub to contact the complaining party, such as an address, telephone number, and, if available, an electronic mail address at which the complaining party may be contacted;</p>
            <p>(v) A statement that the complaining party has a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and</p>
            <p>(vi) A statement that the information in the notification is accurate, and under penalty of perjury, that the complaining party is authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.</p>
            <p>OcuHub’s designated Copyright Agent to receive notifications of claimed infringement is:</p>
            <p>Copyright Agent Tim Neyer, OcuHub LLC; address: 4885 Olde Towne Parkway, Suite 200, Marietta, GA 30068</p>
            <p>email: <a href="mailto:tneyer@OcuHub.com">tneyer@OcuHub.com</a>, telephone: 470-237-4502</p>
            <p>FAILURE TO INCLUDE ALL OF THE ABOVE INFORMATION, ESPECIALLY SPECIFIC INFORMATION ABOUT WHERE INFIRNGING CONTENT MAY BE FOUND, WILL RESULT IN A DELAY IN THE PROCESSING OF YOUR DMCA NOTIFICATION AND MAY RESULT IN YOUR HAVING TO REPEAT SOME OR ALL OF THE ABOVE PROCESS.</p>
            <p>(b)Notice And Takedown. If we receive proper notification of claimed copyright infringement, we will respond expeditiously by removing, or disabling access to, the material that is claimed to be infringing, as described below, or to be the subject of infringing activity. We will also comply with the appropriate provisions of the DMCA in the event a counter-notification is received, as described below.</p>
            <p>We may, at our discretion, deny access to the Service by, or disable and/or terminate the accounts of, Users who may be infringers.</p>
            <p>(c) Copyright Counter-Notices. If content you posted on the Service was removed for copyright or intellectual property infringement, and you would like to dispute that removal, the process for counter-notifications, which is governed by Section 512(g) of the DMCA, is as follows:</p>
            <p>a. To file a counter-notification with us, you must provide our Copyright Agent, at the address set forth above, with a written communication that sets forth the items specified below.</p>
            <p>b. Please note that under Section 512(f) of the DMCA, any person who knowingly materially misrepresents that material or activity was removed or disabled by mistake or misidentification may be subject to liability. Please also be advised that we enforce a policy that provides for the termination, in appropriate circumstances, of the accounts of (or access privileges by) Users who are infringers. Accordingly, if you are not sure whether certain material infringes your copyright or the copyrights of others, we suggest that you first contact an attorney.</p>
            <p>(d) Elements of Counter-Notification. To expedite our ability to process your counter- notification, please use the following format (including section numbers):</p>
            <p>1. Identify the specific URLs of (or other information sufficient to allow us to identify) material that OcuHub has removed or to which OcuHub has disabled access. 2. Provide your full name, address, telephone number, email address and, if you are a registered User, the User name of your OcuHub account. 3. Provide a statement that you consent to the jurisdiction of the Southern District of New York and the Federal District Court for the judicial district in which your address is located (if your address is outside of the U.S.A.), and that you will accept service of process from the person who provided notification to our Copyright Agent in accordance with the process outlined above, or an agent of such person. 4. Include the following statement: “I swear, under penalty of perjury, that I have a good faith belief that the material was removed or disabled as a result of a mistake or misidentification of the material to be removed or disabled.” 5. Sign the notice. If you are providing notice by email, a scanned physical signature or a valid electronic signature will be accepted. Send the communication to the following address:</p>
            <p>Copyright Agent Tim Neyer, OcuHub LLC; address: 4885 Olde Towne Parkway, Suite 200, Marietta, GA 30068</p>
            <p>email: <a href="mailto:tneyer@OcuHub.com">tneyer@OcuHub.com</a>, telephone: 470-237-4502</p>
            <p>After we receive your counter-notification, we will forward it to the party who submitted the original claim of copyright infringement. Please note that when we forward the counter-notification, it includes any of your Identifying Information set forth in the counter-notification. By submitting a counter-notification, you consent to having such Identifying Information revealed in this way. We will not forward the counter-notification to any party other than the original claimant.</p>
            <p>After we send out the counter-notification, the claimant must then notify us within ten (10) days that he or she has filed an action seeking a court order to restrain you from engaging in infringing activity relating to the material on the Service. If we receive such notification, we will be unable to restore the items. If we do not receive such notification, we may, but are not obligated to, reinstate the disputed item(s).</p>
            <p>(e) Foreign Counter-Notification: If you reside outside of the United States, please understand that filing a counter-notice may lead to legal proceedings between you and the complaining party to determine ownership. Be aware that there may be adverse legal consequences in your country and/or the United States of America if you make a false or bad faith allegation by using this process. Please also be advised that we enforce a policy that provides for the termination in appropriate circumstances of access privileges for Users who are infringers. So, if you are not sure whether content you posted on the Service is being infringed, or are otherwise unsure of whether to file a counter-notification using these procedures, we strongly recommend you first contact a lawyer knowledgeable in the laws of the United States and the State of New York. If you do wish to file a counter-notice, you should follow the process set forth above under the heading “Elements of Counter-Notification.”</p>
            <p>(f) Disclaimer: WE ARE NOT YOUR ATTORNEYS, AND THE INFORMATION WE PRESENT HERE IS NOT LEGAL ADVICE. WE PRESENT THIS INFORMATION FOR INFORMATIONAL PURPOSES ONLY.</p>
            <p>24.&nbsp;<strong>Miscellaneous.<br>
</strong>(a) Notice. OcuHub may provide you with notices, including those regarding changes to these Terms, by email, regular mail, or postings on the Service. If Notice is by e-mail or mail, it will be provided to the e-mail or regular mailing address provided by you with your account information and it is your responsibility to update such account information for any changes. Notice to you will be deemed given twenty-four hours after an email is sent, unless OcuHub is notified that the email address is invalid, and if through postal mail, three days after the date of mailing. You may provide OcuHub with notices only by mail to the address indicated in subsection (l) below.</p>
            <p>(b) Governing Law. These Terms shall be governed by and construed in accordance with the laws of the State of California, without giving effect to any principles of conflicts of law.</p>
            <p>(c) Jurisdiction. You agree that any action at law or in equity arising out of or relating to these Terms or the Service shall be filed only in the state or federal courts in and for the County of Santa Diego and State of California and you hereby consent and submit to the personal and exclusive jurisdiction and venue of such courts for the purposes of litigating any such action.</p>
            <p>(d) Waiver. A provision of these Terms may be waived only by a written instrument executed by the party entitled to the benefit of such provision. The failure of OcuHub to exercise or enforce any right or provision of these Terms will not constitute a waiver of such right or provision.</p>
            <p>(e) Severability. If any provision of these Terms shall be unlawful, void, or for any reason unenforceable, then that provision shall be deemed severable from these Terms and shall not affect the validity and enforceability of any remaining provisions.</p>
            <p>(f) Assignment. The Terms and any rights and licenses granted hereunder, may not be transferred or assigned by you, but may be assigned by OcuHub without restriction. Any assignment attempted to be made in violation of these Terms shall be void.</p>
            <p>(g) No Relationship. You agree that no joint venture, partnership, employment, or agency relationship exists between you and OcuHub as a result of these Terms or use of the Service. You further acknowledge that by submitting User Content or other Contributed Content, no confidential, fiduciary, contractually implied or other relationship is created between you and OcuHub other than pursuant to these Terms.</p>
            <p>(h) Survival. Sections 5, 6, 7, 9, 11 (other than your duty to update account information), 13, 15, 16, 17, 18, 19, 20, 21, 22, 23 and 24 will survive any termination of these Terms or your account, whether by you or by OcuHub.</p>
            <p>(i) Headings. The heading references herein are for convenience purposes only, do not constitute a part of these Terms, and shall not be deemed to limit or affect any of the provisions hereof.</p>
            <p>(j) Entire Agreement. This is the entire agreement between you and OcuHub relating to the subject matter herein and supersedes all previous communications, representations, understandings and agreements, either oral or written, between the parties with respect to said subject matter, excluding any Services Agreement that you may have entered into with OcuHub. These Terms shall not be modified except in writing, signed by both parties, or by a change to these Terms made by OcuHub as set forth in Section 3 above.</p>
            <p>(k) CLAIMS. YOU AGREE THAT ANY CAUSE OF ACTION BROUGHT BY YOU ARISING OUT OF OR RELATED TO THE SERVICE MUST COMMENCE WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES. OTHERWISE, SUCH CAUSE OF ACTION IS PERMANENTLY BARRED.</p>
            <p>(l) Disclosures. The services hereunder are offered by OcuHub LLC, located at 4885 Olde Towne Parkway, Suite 200, Marietta, GA 30069.</p>
            <p>(l) Disclosures. The services hereunder are offered by Ocuhub LLC, located at 4885 Olde Towne Parkway, Suite 200, Marietta, GA 30069.</p>
            <div class="clearboth"></div>
        </div>
    </div>

</div>

@endsection
